sudo: required

services:
    - docker

before_install:
    - docker build -t sijojosan/message-board-ui_dev -f ./message-board-ui/Dockerfile.dev ./message-board-ui
    - docker build -t sijojosan/message-board-service_dev -f ./message-board-service/Dockerfile.dev ./message-board-service

script:
    - docker run -e CI=true sijojosan/message-board-ui_dev npm test
    - docker run sijojosan/message-board-service_dev ./mvnw test

after_success:
    - docker build -t sijojosan/message-board-ui ./message-board-ui
    - docker build -t sijojosan/message-board-service ./message-board-service
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push sijojosan/message-board-ui
    - docker push sijojosan/message-board-service